import { test, expect } from '../../../utils/infra/persistent-context';
import { BenefitsTablePage } from '../../../pages/ga/components/benefitsTablePage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * BenefitsTable State Matrix
 *
 * 16 tests (8 valid + 4 responsive + 4 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (8 tests) ──

test.describe('BenefitsTable — State Matrix (Valid)', () => {
    test('[BENEFITS_TABLE-V] @matrix @regression default + light-theme in granite section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + light-theme in azul section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + dark-theme in white section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + dark-theme in slate section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + auto-theme in white section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + auto-theme in slate section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + auto-theme in granite section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-V] @matrix @regression default + auto-theme in azul section', async ({ page }) => {
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (4 tests) ──

test.describe('BenefitsTable — State Matrix (Responsive)', () => {
    test('[BENEFITS_TABLE-R] @matrix @regression @mobile benefits-table in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-R] @matrix @regression @mobile benefits-table in slate section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-R] @matrix @regression @mobile benefits-table in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BENEFITS_TABLE-R] @matrix @regression @mobile benefits-table in azul section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-benefits-table:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (4 tests) ──

test.describe('BenefitsTable — State Matrix (Invalid Combos)', () => {
    test('[BENEFITS_TABLE-N] @matrix @negative @sanity default + light-theme on white (light-on-light)', async ({ page }) => {
      // light-theme on light background (white) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
    });

    test('[BENEFITS_TABLE-N] @matrix @negative @sanity default + light-theme on slate (light-on-light)', async ({ page }) => {
      // light-theme on light background (slate) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
    });

    test('[BENEFITS_TABLE-N] @matrix @negative @sanity default + dark-theme on granite (dark-on-dark)', async ({ page }) => {
      // dark-theme on dark background (granite) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
    });

    test('[BENEFITS_TABLE-N] @matrix @negative @sanity default + dark-theme on azul (dark-on-dark)', async ({ page }) => {
      // dark-theme on dark background (azul) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new BenefitsTablePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
    });
});
