import { test, expect } from '../../../utils/infra/persistent-context';
import { BioCardPage } from '../../../pages/ga/components/bioCardPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * BioCard State Matrix
 *
 * 4 tests (2 valid + 2 responsive + 0 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (2 tests) ──

test.describe('BioCard — State Matrix (Valid)', () => {
    test('[BIO_CARD-V] @matrix @regression default + default in white section', async ({ page }) => {
      const pom = new BioCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-bio-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BIO_CARD-V] @matrix @regression default + default in granite section', async ({ page }) => {
      const pom = new BioCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-bio-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (2 tests) ──

test.describe('BioCard — State Matrix (Responsive)', () => {
    test('[BIO_CARD-R] @matrix @regression @mobile bio-card in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BioCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-bio-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[BIO_CARD-R] @matrix @regression @mobile bio-card in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new BioCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-bio-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (0 tests) ──

test.describe('BioCard — State Matrix (Invalid Combos)', () => {

});
