import { test, expect } from '../../../utils/infra/persistent-context';
import { HomepageHeroPage } from '../../../pages/ga/components/homepageHeroPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * HomepageHero State Matrix
 *
 * 4 tests (2 valid + 1 responsive + 1 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Background: component-level classes on .cmp-homepage-hero
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

// ── Valid: variant × theme × background at desktop (2 tests) ──

test.describe('HomepageHero — State Matrix (Valid)', () => {
    test('[HOMEPAGE_HERO-V] @matrix @regression default + dark-theme in white background', async ({ page }) => {
      const pom = new HomepageHeroPage(page);
      await pom.navigate(BASE());
      const container = page.locator('.cmp-homepage-hero').first();
      await expect(container).toBeVisible();
      const el = container;
      await expect(el).toBeVisible();
    });

    test('[HOMEPAGE_HERO-V] @matrix @regression default + auto-theme in white background', async ({ page }) => {
      const pom = new HomepageHeroPage(page);
      await pom.navigate(BASE());
      const container = page.locator('.cmp-homepage-hero').first();
      await expect(container).toBeVisible();
      const el = container;
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (1 tests) ──

test.describe('HomepageHero — State Matrix (Responsive)', () => {
    test('[HOMEPAGE_HERO-R] @matrix @regression @mobile homepage-hero in white background @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new HomepageHeroPage(page);
      await pom.navigate(BASE());
      const container = page.locator('.cmp-homepage-hero').first();
      await expect(container).toBeVisible();
      const el = container;
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (1 tests) ──

test.describe('HomepageHero — State Matrix (Invalid Combos)', () => {
    test('[HOMEPAGE_HERO-N] @matrix @negative @sanity default + light-theme on white (light-on-light)', async ({ page }) => {
      // light-theme on light background (white) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new HomepageHeroPage(page);
      await pom.navigate(BASE());
      const container = page.locator('.cmp-homepage-hero').first();
      await expect(container).toBeVisible();
    });
});
