import { Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { LocatorStrategy, LocatorEntry } from '../infra/locator-registry';

/**
 * Represents a single interactive element extracted from live DOM.
 */
export interface DOMElement {
  name: string;
  tag: string;
  text: string;
  classes: string[];
  attributes: Record<string, string | null>;
  testId: string | null;
  id: string | null;
  parentClasses: string[];
  role: string | null;
  ariaLabel: string | null;
  isInteractive: boolean;
  boundingBox: { x: number; y: number; width: number; height: number } | null;
}

/**
 * Full DOM snapshot for a component.
 */
export interface DOMSnapshot {
  component: string;
  url: string;
  scannedAt: string;
  rootSelector: string;
  elements: DOMElement[];
  pageTitle: string;
  viewportSize: { width: number; height: number };
}

const SNAPSHOTS_DIR = path.resolve(__dirname, '..', 'data', '.snapshots');

const INTERACTIVE_TAGS = ['a', 'button', 'input', 'select', 'textarea', 'details', 'summary'];
const INTERACTIVE_ROLES = ['button', 'link', 'checkbox', 'radio', 'tab', 'menuitem', 'switch', 'slider', 'combobox', 'textbox'];
const CONTENT_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'img', 'video', 'nav', 'ul', 'ol'];

/**
 * Scan live DOM for a component and extract all interactive/content elements.
 * Saves a snapshot to .snapshots/ for caching.
 */
export async function scanDOM(
  page: Page,
  componentName: string,
  rootSelector?: string
): Promise<DOMSnapshot> {
  // Wait for page stability
  await page.waitForLoadState('networkidle');

  const resolvedRoot = rootSelector || `.ga-${componentName}`;
  const url = page.url();
  const title = await page.title();
  const viewport = page.viewportSize() || { width: 1280, height: 720 };

  // Extract elements from the DOM
  const elements = await page.evaluate(
    ({ root, interactiveTags, interactiveRoles, contentTags }) => {
      const rootEls = document.querySelectorAll(root);
      if (rootEls.length === 0) return [];

      const results: any[] = [];
      const seen = new Set<string>();

      function extractElement(el: Element, index: number): any | null {
        const tag = el.tagName.toLowerCase();
        const id = el.id || null;
        const testId = el.getAttribute('data-testid') || null;
        const classes = Array.from(el.classList);
        const text = (el.textContent || '').trim().slice(0, 100);
        const role = el.getAttribute('role') || null;
        const ariaLabel = el.getAttribute('aria-label') || null;
        const parentEl = el.parentElement;
        const parentClasses = parentEl ? Array.from(parentEl.classList) : [];

        // Determine if interactive
        const isInteractive =
          interactiveTags.includes(tag) ||
          (role && interactiveRoles.includes(role)) ||
          el.hasAttribute('onclick') ||
          el.hasAttribute('tabindex') ||
          el.getAttribute('contenteditable') === 'true';

        // Gather attributes
        const attrs: Record<string, string | null> = {};
        for (const attr of Array.from(el.attributes)) {
          if (['class', 'id', 'style'].includes(attr.name)) continue;
          attrs[attr.name] = attr.value;
        }

        // Get bounding box
        const rect = el.getBoundingClientRect();
        const boundingBox = {
          x: Math.round(rect.x),
          y: Math.round(rect.y),
          width: Math.round(rect.width),
          height: Math.round(rect.height),
        };

        // Generate a unique name — prefer semantic over auto-generated IDs
        // AEM generates IDs like "button-997c248b6d" which are not semantic
        const isAutoGeneratedId = id && /^[a-z]+-[a-f0-9]{6,}$/.test(id);
        let name = '';
        if (testId) {
          name = testId.replace(/[^a-zA-Z0-9]/g, '_');
        } else if (ariaLabel) {
          name = ariaLabel.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_').slice(0, 30);
        } else if (text && text.length > 1 && text.length < 40) {
          name = `${tag}_${text.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_').slice(0, 30)}`;
        } else if (id && !isAutoGeneratedId) {
          name = id.replace(/[^a-zA-Z0-9]/g, '_');
        } else if (tag === 'img') {
          const alt = el.getAttribute('alt') || `image_${index}`;
          name = `img_${alt.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20)}`;
        } else {
          name = `${tag}_${index}`;
        }

        // camelCase
        name = name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
        if (name.match(/^\d/)) name = `el${name}`;

        // Deduplicate
        if (seen.has(name)) {
          name = `${name}_${index}`;
        }
        seen.add(name);

        return {
          name,
          tag,
          text: text.slice(0, 100),
          classes,
          attributes: attrs,
          testId,
          id,
          parentClasses,
          role,
          ariaLabel,
          isInteractive,
          boundingBox,
        };
      }

      // Scan: interactive elements + content elements + BEM sub-elements
      const allSelectors = [
        ...interactiveTags.map((t: string) => `${root} ${t}`),
        ...contentTags.map((t: string) => `${root} ${t}`),
        `${root} [data-testid]`,
        `${root} [role]`,
        `${root} [onclick]`,
        `${root} [tabindex]`,
        // BEM sub-elements: match children with class containing __ (e.g. cmp-statistic__value)
        `${root} [class*="__"]`,
      ];

      let globalIndex = 0;
      for (const selector of allSelectors) {
        try {
          const els = document.querySelectorAll(selector);
          els.forEach((el) => {
            const key = `${el.tagName}-${el.className}-${(el.textContent || '').trim().slice(0, 50)}`;
            if (!seen.has(key)) {
              seen.add(key);
              const extracted = extractElement(el, globalIndex++);
              if (extracted) results.push(extracted);
            }
          });
        } catch {
          // Selector might be invalid, skip
        }
      }

      return results;
    },
    {
      root: resolvedRoot,
      interactiveTags: INTERACTIVE_TAGS,
      interactiveRoles: INTERACTIVE_ROLES,
      contentTags: CONTENT_TAGS,
    }
  );

  const snapshot: DOMSnapshot = {
    component: componentName,
    url,
    scannedAt: new Date().toISOString(),
    rootSelector: resolvedRoot,
    elements: elements as DOMElement[],
    pageTitle: title,
    viewportSize: viewport,
  };

  // Save snapshot
  saveSnapshot(snapshot);

  return snapshot;
}

/**
 * Save a DOM snapshot to the .snapshots/ directory.
 */
function saveSnapshot(snapshot: DOMSnapshot): string {
  if (!fs.existsSync(SNAPSHOTS_DIR)) {
    fs.mkdirSync(SNAPSHOTS_DIR, { recursive: true });
  }
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const filename = `${snapshot.component}_${timestamp}.json`;
  const filePath = path.join(SNAPSHOTS_DIR, filename);
  fs.writeFileSync(filePath, JSON.stringify(snapshot, null, 2), 'utf-8');
  return filePath;
}

/**
 * Load the latest cached snapshot for a component (if exists).
 */
export function loadLatestSnapshot(componentName: string): DOMSnapshot | null {
  if (!fs.existsSync(SNAPSHOTS_DIR)) return null;
  const files = fs.readdirSync(SNAPSHOTS_DIR)
    .filter(f => f.startsWith(`${componentName}_`) && f.endsWith('.json'))
    .sort()
    .reverse();

  if (files.length === 0) return null;

  const raw = fs.readFileSync(path.join(SNAPSHOTS_DIR, files[0]), 'utf-8');
  return JSON.parse(raw) as DOMSnapshot;
}

/**
 * Generate locator strategies for a DOM element.
 * Returns strategies ordered by confidence (highest first).
 */
export function generateStrategies(element: DOMElement, componentName: string): LocatorStrategy[] {
  const strategies: LocatorStrategy[] = [];

  // data-testid (highest confidence)
  if (element.testId) {
    strategies.push({ type: 'testid', value: element.testId, confidence: 1.0 });
  }

  // id
  if (element.id) {
    strategies.push({ type: 'id', value: element.id, confidence: 0.95 });
  }

  // CSS with unique classes
  if (element.classes.length > 0) {
    const cssSelector = element.classes
      .filter(c => !c.startsWith('cq-') && !c.startsWith('aem-'))
      .map(c => `.${c}`)
      .join('');
    if (cssSelector) {
      strategies.push({ type: 'css', value: cssSelector, confidence: 0.8 });
    }
  }

  // Role + name
  if (element.role || element.ariaLabel) {
    const role = element.role || inferRole(element.tag);
    if (role) {
      const value = element.ariaLabel
        ? `${role}[name='${element.ariaLabel.replace(/'/g, "\\'")}']`
        : role;
      strategies.push({ type: 'role', value, confidence: 0.7 });
    }
  }

  // XPath by tag + class combo
  if (element.classes.length > 0) {
    const mainClass = element.classes[0];
    strategies.push({
      type: 'xpath',
      value: `//${element.tag}[contains(@class,'${mainClass}')]`,
      confidence: 0.6,
    });
  }

  // Text content (lowest confidence — text changes frequently)
  if (element.text && element.text.length > 2 && element.text.length < 60) {
    strategies.push({ type: 'text', value: element.text, confidence: 0.4 });
  }

  return strategies.sort((a, b) => b.confidence - a.confidence);
}

/**
 * Convert a DOMElement to a LocatorEntry with generated strategies.
 */
export function elementToLocatorEntry(element: DOMElement, componentName: string): LocatorEntry {
  return {
    name: element.name,
    component: componentName,
    strategies: generateStrategies(element, componentName),
  };
}

function inferRole(tag: string): string | null {
  const roleMap: Record<string, string> = {
    a: 'link',
    button: 'button',
    input: 'textbox',
    select: 'combobox',
    textarea: 'textbox',
    nav: 'navigation',
    h1: 'heading',
    h2: 'heading',
    h3: 'heading',
    h4: 'heading',
    h5: 'heading',
    h6: 'heading',
    img: 'img',
  };
  return roleMap[tag] || null;
}
