import { test, expect } from '../infra/persistent-context';
import { SectionPage } from '../../../pages/ga/components/sectionPage';
import ENV from '../infra/env';
import { loginToAEMAuthor } from '../infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * Section State Matrix
 *
 * 8 tests (4 valid + 4 responsive + 0 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (4 tests) ──

test.describe('Section — State Matrix (Valid)', () => {
    test('[SECTION-V] @matrix @regression default + default in white section', async ({ page }) => {
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-V] @matrix @regression default + default in slate section', async ({ page }) => {
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-V] @matrix @regression default + default in granite section', async ({ page }) => {
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-V] @matrix @regression default + default in azul section', async ({ page }) => {
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (4 tests) ──

test.describe('Section — State Matrix (Responsive)', () => {
    test('[SECTION-R] @matrix @regression @mobile section in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-R] @matrix @regression @mobile section in slate section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-R] @matrix @regression @mobile section in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[SECTION-R] @matrix @regression @mobile section in azul section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new SectionPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('azul')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-section:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (0 tests) ──

test.describe('Section — State Matrix (Invalid Combos)', () => {

});
