import { test, expect } from '../../../utils/infra/persistent-context';
import { VideoExternalPage } from '../../../pages/ga/components/videoExternalPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * VideoExternal State Matrix
 *
 * 8 tests (4 valid + 2 responsive + 2 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :visible:not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (4 tests) ──

test.describe('VideoExternal — State Matrix (Valid)', () => {
    test('[VIDEO_EXTERNAL-V] @matrix @regression default + light-theme in granite section', async ({ page }) => {
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[VIDEO_EXTERNAL-V] @matrix @regression default + dark-theme in white section', async ({ page }) => {
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[VIDEO_EXTERNAL-V] @matrix @regression default + auto-theme in white section', async ({ page }) => {
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[VIDEO_EXTERNAL-V] @matrix @regression default + auto-theme in granite section', async ({ page }) => {
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (2 tests) ──

test.describe('VideoExternal — State Matrix (Responsive)', () => {
    test('[VIDEO_EXTERNAL-R] @matrix @regression @mobile video-external in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[VIDEO_EXTERNAL-R] @matrix @regression @mobile video-external in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-video-external:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (2 tests) ──

test.describe('VideoExternal — State Matrix (Invalid Combos)', () => {
    test('[VIDEO_EXTERNAL-N] @matrix @negative @sanity default + light-theme on white (light-on-light)', async ({ page }) => {
      // light-theme on light background (white) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
    });

    test('[VIDEO_EXTERNAL-N] @matrix @negative @sanity default + dark-theme on granite (dark-on-dark)', async ({ page }) => {
      // dark-theme on dark background (granite) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new VideoExternalPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
    });
});
