import { test, expect } from '../../../utils/infra/persistent-context';
import { ContentHighlightPage } from '../../../pages/ga/components/contentHighlightPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * ContentHighlight State Matrix
 *
 * 8 tests (4 valid + 2 responsive + 2 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (4 tests) ──

test.describe('ContentHighlight — State Matrix (Valid)', () => {
    test('[CONTENT_HIGHLIGHT-V] @matrix @regression default + light-theme in granite section', async ({ page }) => {
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[CONTENT_HIGHLIGHT-V] @matrix @regression default + dark-theme in slate section', async ({ page }) => {
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[CONTENT_HIGHLIGHT-V] @matrix @regression default + auto-theme in slate section', async ({ page }) => {
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[CONTENT_HIGHLIGHT-V] @matrix @regression default + auto-theme in granite section', async ({ page }) => {
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (2 tests) ──

test.describe('ContentHighlight — State Matrix (Responsive)', () => {
    test('[CONTENT_HIGHLIGHT-R] @matrix @regression @mobile content-highlight in slate section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[CONTENT_HIGHLIGHT-R] @matrix @regression @mobile content-highlight in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-content-highlight:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (2 tests) ──

test.describe('ContentHighlight — State Matrix (Invalid Combos)', () => {
    test('[CONTENT_HIGHLIGHT-N] @matrix @negative default + light-theme on slate (light-on-light)', async ({ page }) => {
      // light-theme on light background (slate) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('slate')).first();
      await expect(container).toBeVisible();
    });

    test('[CONTENT_HIGHLIGHT-N] @matrix @negative default + dark-theme on granite (dark-on-dark)', async ({ page }) => {
      // dark-theme on dark background (granite) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new ContentHighlightPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
    });
});
