import { test, expect } from '../../../utils/infra/persistent-context';
import { ProductPathDetailCardPage } from '../../../pages/ga/components/productPathDetailCardPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * ProductPathDetailCard State Matrix
 *
 * 4 tests (2 valid + 1 responsive + 1 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (2 tests) ──

test.describe('ProductPathDetailCard — State Matrix (Valid)', () => {
    test('[PRODUCT_PATH_DETAIL_CARD-V] @matrix @regression default + dark-theme in white section', async ({ page }) => {
      const pom = new ProductPathDetailCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-path-detail-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[PRODUCT_PATH_DETAIL_CARD-V] @matrix @regression default + auto-theme in white section', async ({ page }) => {
      const pom = new ProductPathDetailCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-path-detail-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (1 tests) ──

test.describe('ProductPathDetailCard — State Matrix (Responsive)', () => {
    test('[PRODUCT_PATH_DETAIL_CARD-R] @matrix @regression @mobile product-path-detail-card in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new ProductPathDetailCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-path-detail-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (1 tests) ──

test.describe('ProductPathDetailCard — State Matrix (Invalid Combos)', () => {
    test('[PRODUCT_PATH_DETAIL_CARD-N] @matrix @negative @sanity default + light-theme on white (light-on-light)', async ({ page }) => {
      // light-theme on light background (white) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new ProductPathDetailCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
    });
});
