import { test, expect } from '../../../utils/infra/persistent-context';
import { ProductComparisonCardPage } from '../../../pages/ga/components/productComparisonCardPage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * ProductComparisonCard State Matrix
 *
 * 4 tests (2 valid + 1 responsive + 1 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (2 tests) ──

test.describe('ProductComparisonCard — State Matrix (Valid)', () => {
    test('[PRODUCT_COMPARISON_CARD-V] @matrix @regression default + light-theme in granite section', async ({ page }) => {
      const pom = new ProductComparisonCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-comparison-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[PRODUCT_COMPARISON_CARD-V] @matrix @regression default + auto-theme in granite section', async ({ page }) => {
      const pom = new ProductComparisonCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-comparison-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (1 tests) ──

test.describe('ProductComparisonCard — State Matrix (Responsive)', () => {
    test('[PRODUCT_COMPARISON_CARD-R] @matrix @regression @mobile product-comparison-card in granite section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new ProductComparisonCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
      const el = container.locator('.cmp-product-comparison-card:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (1 tests) ──

test.describe('ProductComparisonCard — State Matrix (Invalid Combos)', () => {
    test('[PRODUCT_COMPARISON_CARD-N] @matrix @negative default + dark-theme on granite (dark-on-dark)', async ({ page }) => {
      // dark-theme on dark background (granite) has insufficient contrast
      // Auto-theme should be used instead. Verify container still renders.
      const pom = new ProductComparisonCardPage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('granite')).first();
      await expect(container).toBeVisible();
    });
});
