import { test, expect } from '../../../utils/infra/persistent-context';
import { AccordionTabsFeaturePage } from '../../../pages/ga/components/accordionTabsFeaturePage';
import ENV from '../../../utils/infra/env';
import { loginToAEMAuthor } from '../../../utils/infra/auth-fixture';

const BASE = () => ENV.AEM_AUTHOR_URL || 'http://localhost:4502';

test.beforeEach(async ({ page }) => {
  await loginToAEMAuthor(page);
});

/*
 * AccordionTabsFeature State Matrix
 *
 * 3 tests (2 valid + 1 responsive + 0 invalid).
 * Generated by state-matrix-generator.ts — viewport triplication collapsed.
 *
 * Selectors (from DOM probe):
 *   Section: .cmp-section--background-color-{bg}
 *   Disabled overlays excluded via :visible:not([aria-disabled="true"])
 */

/** Section CSS class for a given background (from live AEM DOM) */
function sectionSel(bg: string) {
  return `.cmp-section--background-color-${bg}`;
}

// ── Valid: variant × theme × background at desktop (2 tests) ──

test.describe('AccordionTabsFeature — State Matrix (Valid)', () => {
    test('[ACCORDION_TABS_FEATURE-V] @matrix @regression behavior-accordion + default in white section', async ({ page }) => {
      const pom = new AccordionTabsFeaturePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      // Was accidentally self-nested (".cmp-accordion-tabs-feature ... .cmp-accordion-tabs-feature"),
      // requiring a second instance of the component inside itself — matches 0 elements live.
      // The :visible:not([aria-disabled="true"]) filter is meant to apply to the component root
      // itself (excluding disabled overlays), not gate a descendant of the same class.
      const el = container.locator('.cmp-accordion-tabs-feature:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });

    test('[ACCORDION_TABS_FEATURE-V] @matrix @regression behavior-scroll + default in white section', async ({ page }) => {
      const pom = new AccordionTabsFeaturePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      // Was accidentally self-nested (".cmp-accordion-tabs-feature ... .cmp-accordion-tabs-feature"),
      // requiring a second instance of the component inside itself — matches 0 elements live.
      // The :visible:not([aria-disabled="true"]) filter is meant to apply to the component root
      // itself (excluding disabled overlays), not gate a descendant of the same class.
      const el = container.locator('.cmp-accordion-tabs-feature:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Responsive: one spot-check per background at mobile (1 tests) ──

test.describe('AccordionTabsFeature — State Matrix (Responsive)', () => {
    test('[ACCORDION_TABS_FEATURE-R] @matrix @regression @mobile accordion-tabs-feature in white section @ mobile-390', async ({ page }) => {
      await page.setViewportSize({ width: 390, height: 844 });
      const pom = new AccordionTabsFeaturePage(page);
      await pom.navigate(BASE());
      const container = page.locator(sectionSel('white')).first();
      await expect(container).toBeVisible();
      // Was accidentally self-nested (".cmp-accordion-tabs-feature ... .cmp-accordion-tabs-feature"),
      // requiring a second instance of the component inside itself — matches 0 elements live.
      // The :visible:not([aria-disabled="true"]) filter is meant to apply to the component root
      // itself (excluding disabled overlays), not gate a descendant of the same class.
      const el = container.locator('.cmp-accordion-tabs-feature:visible:not([aria-disabled="true"])').first();
      await expect(el).toBeVisible();
    });
});

// ── Invalid: contrast concerns (0 tests) ──

test.describe('AccordionTabsFeature — State Matrix (Invalid Combos)', () => {

});
